contacts/Models/Contact.cs
using System.Collections.Generic;

namespace Contacts.Models
{
    public class Contact : BaseModel
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }

        public int UserID { get; set; }

        public virtual User User { get; set; }

        public virtual List<Phone> Phones { get; set; }

        public virtual string FullName => $"{FirstName} {LastName}";
    }
}

contacts/ViewModels/Contacts/ContactCreateEditVM.cs
using Contacts.Models;
using System.ComponentModel.DataAnnotations;

namespace Contacts.ViewModels.Contacts
{
    public class ContactCreateEditVM : BaseVM
    {
        [Required]
        [Display(Name = "نام")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "نام خانوادگی")]
        public string LastName { get; set; }

        [EmailAddress]
        [Display(Name = "ایمیل")]
        public string Email { get; set; }

        public int UserID { get; set; }

        public User User { get; set; }
    }
}

contacts/ViewModels/Contacts/ContactsListVM.cs
using Contacts.Models;
using PagedList;

namespace Contacts.ViewModels.Contacts
{
    public class ContactsListVM : BaseListVM<Contact>
    {
        public PagedList<Contact> PagedContacts { get; set; }

        public int? Page { get; set; }

        public string SearchString { get; set; }
    }
}

contacts/Controllers/ContactsController.cs
using Contacts.Models;
using PagedList;
using Contacts.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using System.Web.Routing;
using Contacts.ViewModels.Contacts;
using Contacts.Filters;
using AutoMapper;

namespace Contacts.Controllers
{
    [Authenticate]
    public class ContactsController : Controller
    {
        public ActionResult Index()
        {
            ContactsListVM model = new ContactsListVM();

            TryUpdateModel(model);
            UnitOfWork unitOfWork = new UnitOfWork();

            //ContactRepository contactRepo = new ContactRepository();

            User user = AuthenticationService.LoggedUser;

            Expression<Func<Contact, bool>> filter = null;

            if (!string.IsNullOrEmpty(model.SearchString)) // With Searching
            {
                string[] searchArray = model.SearchString.Split(new char[0], StringSplitOptions.RemoveEmptyEntries);

                filter = c => (c.UserID == user.ID) && (searchArray.Any(word => c.FirstName.Contains(word))
                                                     || searchArray.Any(word => c.LastName.Contains(word))
                                                     || searchArray.Any(word => c.Email.Contains(word)));
            }

            else // Without Searching
            {
                filter = c => c.UserID == user.ID;
            }

            //model.Entities = contactRepo.GetAll(filter);
            model.Entities = unitOfWork.ContactRepository.GetAllContacts(filter);
            // Paging

            int pageSize = 2;
            int pageNumber = (model.Page ?? 1);

            model.PagedContacts = new PagedList<Contact>(model.Entities, pageNumber, pageSize);

            return View(model);
        }

        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                UnitOfWork unitOfWork = new UnitOfWork();
                //ContactRepository contactRepo = new ContactRepository();

                //Contact contact = contactRepo.GetById(id.Value);
                Contact contact = unitOfWork.ContactRepository.GetContactById(id.Value);

                if (contact != null && contact.UserID == AuthenticationService.LoggedUser.ID)
                {
                    var mapper = Mapper.Instance;
                    var model = mapper.Map<ContactCreateEditVM>(contact);
                    //ContactCreateEditVM model = new ContactCreateEditVM()
                    //{
                    //    ID = contact.ID,
                    //    FirstName = contact.FirstName,
                    //    LastName = contact.LastName,
                    //    Email = contact.Email
                    //};
                    return View(model);
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult CreateEdit(int? id)
        {
            if (id == null) // Create
            {
                ContactCreateEditVM model = new ContactCreateEditVM()
                {
                    UserID = AuthenticationService.LoggedUser.ID
                };
                return View(model);
            }

            if (id > 0) // Edit
            {
                //ContactRepository contactRepo = new ContactRepository();

                //Contact contact = contactRepo.GetById(id.Value);
                UnitOfWork unitOfWork = new UnitOfWork();
                Contact contact = unitOfWork.ContactRepository.GetContactById(id.Value);

                if (contact != null && contact.UserID == AuthenticationService.LoggedUser.ID)
                {
                    var mapper = Mapper.Instance;
                    var model = mapper.Map<ContactCreateEditVM>(contact);
                    //ContactCreateEditVM model = new ContactCreateEditVM()
                    //{
                    //    ID = contact.ID,
                    //    UserID = contact.UserID,
                    //    FirstName = contact.FirstName,
                    //    LastName = contact.LastName,
                    //    Email = contact.Email
                    //};
                    return View(model);
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEdit(ContactCreateEditVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Contact contact;

            //ContactRepository contactRepo = new ContactRepository();
            UnitOfWork unitOfWork = new UnitOfWork();

            if (model.ID > 0) // Edit
            {
                //contact = contactRepo.GetById(model.ID);
                contact = unitOfWork.ContactRepository.GetContactById(model.ID);

                if (contact == null || contact.UserID != model.UserID)
                {
                    unitOfWork.Dispose();
                    return HttpNotFound();
                }
            }

            else // Create
            {
                contact = new Contact()
                {
                    UserID = model.UserID,
                };
            }

            if (contact.UserID == AuthenticationService.LoggedUser.ID)
            {
                contact.FirstName = model.FirstName;
                contact.LastName = model.LastName;
                contact.Email = model.Email;

                //contactRepo.Save(contact);
                unitOfWork.ContactRepository.Save(contact);
                unitOfWork.Dispose();

                return RedirectToAction("Index");
            }

            return HttpNotFound();
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                //ContactRepository contactRepo = new ContactRepository();
                //Contact contact = contactRepo.GetById(id.Value);
                UnitOfWork unitOfWork = new UnitOfWork();
                Contact contact = unitOfWork.ContactRepository.GetContactById(id.Value);

                if (contact != null && contact.UserID == AuthenticationService.LoggedUser.ID)
                {
                    var mapper = Mapper.Instance;
                    var model = mapper.Map<ContactCreateEditVM>(contact);
                    //ContactCreateEditVM model = new ContactCreateEditVM()
                    //{
                    //    ID = contact.ID,
                    //    FirstName = contact.FirstName,
                    //    LastName = contact.LastName,
                    //    Email = contact.Email
                    //};
                    return View(model);
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id != null)
            {
                //ContactRepository contactRepo = new ContactRepository();
                //Contact contact = contactRepo.GetById(id.Value);
                UnitOfWork unitOfWork = new UnitOfWork();
                Contact contact = unitOfWork.ContactRepository.GetContactById(id.Value);

                if (contact != null && contact.UserID == AuthenticationService.LoggedUser.ID)
                {
                    unitOfWork.ContactRepository.DeleteContact(contact);
                    return RedirectToAction("Index");
                }
            }

            return HttpNotFound();
        }
    }
}

contacts/Controllers/PhonesController.cs
using Contacts.Models;
using Contacts.ViewModels.Phones;
using Contacts.Services;
using Contacts.Filters;
using System.Web.Mvc;
using AutoMapper;
using Contacts.ViewModels.Contacts;

namespace Contacts.Controllers
{
    [Authenticate]
    public class PhonesController : Controller
    {
        // Gets contact by id if contact's user is logged in
        private Contact GetUserContact(int contactId)
        {
            //ContactRepository contactRepo = new ContactRepository();
            //Contact contact = contactRepo.GetById(contactId);
            UnitOfWork unitOfWork = new UnitOfWork();
            Contact contact = unitOfWork.ContactRepository.GetContactById(contactId);

            return contact == null || contact.UserID != AuthenticationService.LoggedUser.ID ? null : contact;
        }

        // Check if contact's user is logged in
        private bool CheckIfContactsUserIsLogged(Phone phone)
        {
            Contact contact = GetUserContact(phone.ContactID);

            return contact != null;
        }

        // INDEX

        public ActionResult Index(int? id) //contactID
        {
            if (id != null)
            {
                Contact contact = GetUserContact(id.Value);

                if (contact != null)
                {
                    PhonesListVM model = new PhonesListVM()
                    {
                        Contact = contact
                    };

                    model.Entities = model.Contact.Phones;

                    return View(model);
                }
            }

            return HttpNotFound();
        }

        public ActionResult CreateEdit(int? id, int? contactId)
        {
            if (id == null && contactId != null) // Create
            {
                Contact contact = GetUserContact(contactId.Value);

                if (contact != null)
                {
                    return View(new PhoneCreateEditVM()
                    {
                        Contact = contact
                    });
                }
            }

            if (id > 0) // Edit
            {
                //PhoneRepository phoneRepo = new PhoneRepository();
                //Phone phone = phoneRepo.GetById(id.Value);
                UnitOfWork unitOfWork = new UnitOfWork();
                Phone phone = unitOfWork.PhoneRepository.GetPhoneById(id.Value);

                if (phone != null && CheckIfContactsUserIsLogged(phone))
                {
                    var mapper = Mapper.Instance;
                    var p = mapper.Map<PhoneCreateEditVM>(phone);
                    //PhoneCreateEditVM p = new PhoneCreateEditVM()
                    //{
                    //    ID = phone.ID,
                    //    Contact = phone.Contact,
                    //    ContactID = phone.ContactID,
                    //    PhoneNumber = phone.PhoneNumber
                    //};

                    return View(p);
                }
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEdit(PhoneCreateEditVM model)
        {
            Contact contact = GetUserContact(model.ContactID);

            if (contact == null)
            {
                return HttpNotFound();
            }

            model.Contact = contact;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Phone phone;

            //PhoneRepository phoneRepo = new PhoneRepository();
            UnitOfWork unitOfWork = new UnitOfWork();

            if (model.ID > 0) // Edit
            {
                //phone = phoneRepo.GetById(model.ID);
                phone = unitOfWork.PhoneRepository.GetPhoneById(model.ID);

                if (phone == null || phone.ContactID != model.ContactID)
                {
                    return HttpNotFound();
                }
            }

            else // Create
            {
                phone = new Phone()
                {
                    ContactID = model.ContactID
                };
            }

            phone.PhoneNumber = model.PhoneNumber;

            //phoneRepo.Save(phone);
            unitOfWork.PhoneRepository.Save(phone);

            return RedirectToAction("Index", new { id = phone.ContactID });
        }

        public ActionResult Delete(int? id) // phoneID
        {
            if (id != null)
            {
                //PhoneRepository phoneRepo = new PhoneRepository();
                //Phone phone = phoneRepo.GetById(id.Value);
                UnitOfWork unitOfWork = new UnitOfWork();
                Phone phone = unitOfWork.PhoneRepository.GetPhoneById(id.Value);

                if (phone != null && CheckIfContactsUserIsLogged(phone))
                {
                    var mapper = Mapper.Instance;
                    var p = mapper.Map<PhoneCreateEditVM>(phone);
                    //PhoneCreateEditVM p = new PhoneCreateEditVM()
                    //{
                    //    ID = phone.ID,
                    //    Contact = phone.Contact,
                    //    PhoneNumber = phone.PhoneNumber
                    //};

                    return View(p);
                }
            }

            return HttpNotFound();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id) // phoneID
        {
            if (id != null)
            {
                //PhoneRepository phoneRepo = new PhoneRepository();
                //Phone phone = phoneRepo.GetById(id.Value);
                UnitOfWork unitOfWork = new UnitOfWork();
                Phone phone = unitOfWork.PhoneRepository.GetPhoneById(id.Value);

                if (phone != null && CheckIfContactsUserIsLogged(phone))
                {
                    //phoneRepo.Delete(phone);
                    unitOfWork.PhoneRepository.DeletePhone(phone);

                    return RedirectToAction("Index", new { id = phone.ContactID });
                }
            }

            return HttpNotFound();
        }
    }
}

contacts/Views/Contacts/CreateEdit.cshtml
@using Contacts.ViewModels.Contacts
@model ContactCreateEditVM

@{
    var title = Model == null || Model.ID == 0 ? "ایجاد" : "ویرایش";
    ViewBag.Title = title;
}

<h2>@title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>مخاطب</h4>
        <hr />
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.UserID)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@title" class="btn btn-success" />
                @Html.ActionLink("بازگشت", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}

contacts/Views/Contacts/Delete.cshtml
@using Contacts.ViewModels.Contacts
@model ContactCreateEditVM

<h3>مطمئنی میخوای حذفش کنی؟</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="بلی" class="btn btn-danger" />
            @Html.ActionLink("بازگشت", "Index", null, new { @class = "btn btn-secondary" })
        </div>
    }
</div>

contacts/Views/Contacts/Details.cshtml
@using Contacts.ViewModels.Contacts
@model ContactCreateEditVM

<div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("ویرایش", "CreateEdit", new { id = Model.ID }, new { @class = "btn btn-success" })
    @Html.ActionLink("بازگشت", "Index", null, new { @class = "btn btn-secondary" })
</p>

contacts/Views/Contacts/Index.cshtml
@using Contacts.ViewModels.Contacts
@using PagedList.Mvc
@model ContactsListVM

@section styles
{
    @Styles.Render("~/Content/PagedList")
}

@{
    ViewBag.Title = "فهرست مخاطبین";
}

<h2>مخاطبین</h2>

<p>
    @Html.ActionLink("افزودن مخاطب جدید", "CreateEdit", null, new { @class = "btn btn-primary" })
</p>

@using (Html.BeginForm("Index", "Contacts", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="form-group">
        <label for="searchString" class="sr-only">جستجو</label>
        @Html.TextBox("SearchString", Model.SearchString as string, new { id = "searchString", @class = "form-control mb-2 mr-sm-2" })
    </div>
    <button type="submit" class="btn btn-info mb-2">جستجو</button>
}

<table class="table table-hover table-borderless">

    @foreach (var item in Model.PagedContacts)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("شماره ها", "Index", "Phones", new { id = item.ID }, new { @class = "btn btn-outline-info" })
            </td>
            <td>
                @Html.ActionLink("ویرایش", "CreateEdit", new { id = item.ID }, new { @class = "btn btn-outline-success" })
                @Html.ActionLink("جزئيات", "Details", new { id = item.ID }, new { @class = "btn btn-outline-secondary" })
                @Html.ActionLink("حذف", "Delete", new { id = item.ID }, new { @class = "btn btn-outline-danger" })
            </td>
        </tr>
    }

</table>

<br />

<h3>
@Html.PagedListPager(Model.PagedContacts, page => Url.Action("Index", new { page, searchString = Model.SearchString }))
</h3>